# Generated by Django 4.1.7 on 2024-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner_image",
            field=models.ImageField(
                default="profile_default.png", upload_to="", verbose_name="banner image"
            ),
        ),
    ]
