# Generated by Django 4.1.7 on 2024-08-08 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="prfile_photo",
            new_name="profile_photo",
        ),
    ]
