# Generated by Django 4.1.7 on 2024-08-09 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_rename_prfile_photo_profile_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="flowwers",
            new_name="followers",
        ),
    ]
